In [4]:
from src.api.api import API
import os
import pandas as pd

In [5]:
def gravar_dados_linha():
    lista_temp=  []
    caminho = os.getcwd() + '/data/datalake/bronze/arquivos_gtfs/routes.txt'
    obter_dados_linha = API.ober_dados_linha('1012-10')
    print(obter_dados_linha)


    print(caminho)

    base_linha = pd.read_csv(caminho)
    for indice, valor in base_linha.iterrows():
        print(indice)
        dados_linha = API.ober_dados_linha(valor['route_id'])
        dados_dict = {
            'LINHA': valor['route_id'],
            'CODIGO_AREA': dados_linha[1],
            'CONSOCIO': dados_linha[2],
            'EMPRESA': dados_linha[3]
        }

        lista_temp.append(dados_dict)
    df = pd.DataFrame(lista_temp)
    df.to_csv(os.getcwd() + '/data/datalake/bronze/relacao_empresas.csv')

In [6]:
gravar_dados_linha()

('1012-10', '1', 'CONSÓRCIO TRANSNOROESTE', 'NORTE BUSS TRANSPORTES S.A.')
/home/rodrigo/projetos/monitoramento_sptrans/data/datalake/bronze/arquivos_gtfs/routes.txt
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39

In [ ]:
base_linha = pd.read_csv('../data/datalake/bronze/arquivos_gtfs/routes.txt')
base_linha.head()

,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color
0,1012-10,1,1012-10,Term. Jd. Britania - Jd. Monte Belo,3,509E2F,FFFFFF
1,1012-21,1,1012-21,Term. Jd. Britânia - Jd. Rosinha,3,509E2F,FFFFFF
2,1015-10,1,1015-10,Term. Jd. Britânia - Chác. Maria Trindade,3,509E2F,FFFFFF
3,1016-10,1,1016-10,Cem. Do Horto - Shop. Center Norte,3,002F6C,FFFFFF
4,1017-10,1,1017-10,Perus - Conexão Vl. Iório,3,509E2F,FFFFFF

In [ ]:
for indice_linha, valor_linha in base_linha.iterrows():
    print(indice_linha, base_linha['route_id'])

0 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
1 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
2 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
3 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
4 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
5 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
6 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
7 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
8 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
9 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
10 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
11 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
12 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
13 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
14 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
15 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
16 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
17 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
18 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
19 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
20 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
21 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
22 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
23 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
24 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
25 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
26 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
27 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
28 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
29 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
30 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
31 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
32 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
33 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
34 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
35 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
36 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
37 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
38 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
39 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
40 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
41 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
42 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
43 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
44 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
45 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
46 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
47 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
48 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
49 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
50 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
51 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
52 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
53 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
54 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
55 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
56 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
57 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
58 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
59 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
60 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
61 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
62 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
63 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
64 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
65 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
66 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
67 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
68 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
69 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
70 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
71 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
72 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
73 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
74 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
75 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
76 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
77 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
78 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
79 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
80 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
81 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
82 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
83 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
84 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
85 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
86 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
87 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
88 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
89 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11
Name: route_id, Length: 1322, dtype: object
90 0       1012-10
1       1012-21
2       1015-10
3       1016-10
4       1017-10
         ...
1317    N839-11
1318    N840-11
1319    N841-11
1320    N842-11
1321    N843-11